image: golang:alpine

stages:
  - test

before_script:
  - apk add --no-cache git build-base bash make
  - mkdir -p /go/src/gitlab.com/$CI_PROJECT_NAMESPACE /go/src/_/builds
  - cp -r $CI_PROJECT_DIR /go/src/gitlab.com/$CI_PROJECT_PATH
  - ln -s /go/src/gitlab.com/$CI_PROJECT_NAMESPACE /go/src/_/builds/$CI_PROJECT_NAMESPACE
  - make dep

unit_tests:
  stage: test
  script:
    - make test

code_coverage:
  stage: test
  script:
    - make coverage
  coverage: '/^coverage:\s(\d+(?:\.\d+)?%)/'